spring:
  application:
    name: config
server:
  port: 19005
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:19000/eureka

spring:
  cloud:
    config:
      server:
        git:
          uri: http://10.17.41.24:10080
          searchPaths: meicloud/config.git
          username: jenkins_user
          password: jenkins_pwd
      label: master