# 下面整个树都非必须，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
#zuul:
#  routes:
#    user: # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
#      path: /user/** # 想要映射到的路径
#      service-id: microservice-provider-user # Eureka中的serviceId
spring:
  application:
    name: gateway
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9000/eureka
zuul:
  routes:
    users:
      path: /user/**
      serviceId: authorization-service
    dict:
      path: /dict/**
      serviceId: dict-service
    web-framework:
      path: /web/**
      serviceId: web-framework
  add-host-header: true
  sensitive-headers:
ribbon:
  restclient:
    enabled: true